Collections
Eugenio36/codelex-exercises pull request #10
Opened 2022-03-25 10:40 UTC by Eugenio36

2022-04-10 14:06 UTC, NilsKula requested changes

2022-04-10 14:06 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/FlightPlanner.java
> +        while (true) {
katro no while varētu uz palīgmetodi, būs daudz pārskatāmak

2022-04-10 14:06 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/Histogram.java
> +    private static String fileContent() throws URISyntaxException, IOException {
private metodes aiz public

2022-04-10 14:06 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/Histogram.java
> +            } else if (scoreAsNumber >= 10 && scoreAsNumber <= 19) {
pietiek `scoreAsNumber <= 19` zini jau ka nav zem 10

2022-04-10 14:06 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/phonebook/PhoneEntry.java
> +    String name;
private

2022-04-10 14:06 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/phonebook/PhoneDirectoryEdited.java
> +        for (Map.Entry<String, String> i : data.entrySet()) {
sķiet jau ka šeit pilnība pietiktu ar `data.get()`

2022-04-12 12:39 UTC, Eugenio36 commented on src/main/java/io/codelex/collections/practice/Histogram.java
> +    private static String fileContent() throws URISyntaxException, IOException {
Salabots.

2022-04-12 12:39 UTC, Eugenio36 commented on src/main/java/io/codelex/collections/practice/Histogram.java
> +            } else if (scoreAsNumber >= 10 && scoreAsNumber <= 19) {
Salabots.

2022-04-12 12:39 UTC, Eugenio36 commented on src/main/java/io/codelex/collections/practice/phonebook/PhoneEntry.java
> +    String name;
Salabots.

2022-04-12 12:39 UTC, Eugenio36 commented on src/main/java/io/codelex/collections/practice/phonebook/PhoneDirectoryEdited.java
> +        for (Map.Entry<String, String> i : data.entrySet()) {
Salabots.

2022-04-15 17:47 UTC, NilsKula approved these changes

2022-04-17 07:06 UTC, merged